<a href="https://colab.research.google.com/github/supachaya2535/PM2.5-Prediction/blob/master/Lecture_01_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
from sklearn import datasets

In [0]:
iris = datasets.load_iris()
iris.data

In [0]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [0]:
X = pd.DataFrame( iris.data , columns = iris['feature_names']  )
Y = pd.DataFrame( iris['target'],columns = ['target'])
X.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state = 42)

In [0]:
X_train.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
81                 5.5               2.4                3.7               1.0
133                6.3               2.8                5.1               1.5
137                6.4               3.1                5.5               1.8
75                 6.6               3.0                4.4               1.4
109                7.2               3.6                6.1               2.5

In [0]:
from sklearn.metrics.pairwise import euclidean_distances

x0 = X_test.iloc[1][:]

In [0]:
X_test.head(5)
dist = euclidean_distances(X_train, [x0])
print('index = ',dist.argmax())
print('max dist = ', dist.max())

print(dist)

In [0]:
k=3
for i in range(0,X_test.shape[0]):
  Class_Y = Y_train.copy()
  x0 = X_test.iloc[i][:]
  Class_Y['dist'] = euclidean_distances(X_train, [x0]).copy()
  Class_Y.sort_values(by='dist', ascending=True,  inplace=True)
  vote = np.array([0,0,0])
  
  for j in range(k):
    vote[Class_Y['target'].iloc[j]] = vote[Class_Y['target'].iloc[j]]+1
  print(vote)
  idx_min = vote.argmax()
  
  print('#',i,'Desired:',Y_test['target'].iloc[i],'-->Predict :', idx_min)

[0 3 0]
# 0 Desired: 1 -->Predict : 1
[3 0 0]
# 1 Desired: 0 -->Predict : 0
[0 0 3]
# 2 Desired: 2 -->Predict : 2
[0 3 0]
# 3 Desired: 1 -->Predict : 1
[0 3 0]
# 4 Desired: 1 -->Predict : 1
[3 0 0]
# 5 Desired: 0 -->Predict : 0
[0 3 0]
# 6 Desired: 1 -->Predict : 1
[0 0 3]
# 7 Desired: 2 -->Predict : 2
[0 2 1]
# 8 Desired: 1 -->Predict : 1
[0 3 0]
# 9 Desired: 1 -->Predict : 1
[0 1 2]
# 10 Desired: 2 -->Predict : 2
[3 0 0]
# 11 Desired: 0 -->Predict : 0
[3 0 0]
# 12 Desired: 0 -->Predict : 0
[3 0 0]
# 13 Desired: 0 -->Predict : 0
[3 0 0]
# 14 Desired: 0 -->Predict : 0
[0 2 1]
# 15 Desired: 1 -->Predict : 1
[0 0 3]
# 16 Desired: 2 -->Predict : 2
[0 3 0]
# 17 Desired: 1 -->Predict : 1
[0 3 0]
# 18 Desired: 1 -->Predict : 1
[0 0 3]
# 19 Desired: 2 -->Predict : 2
[3 0 0]
# 20 Desired: 0 -->Predict : 0
[0 0 3]
# 21 Desired: 2 -->Predict : 2
[3 0 0]
# 22 Desired: 0 -->Predict : 0
[0 0 3]
# 23 Desired: 2 -->Predict : 2
[0 0 3]
# 24 Desired: 2 -->Predict : 2
[0 0 3]
# 25 Desired: 2 -->Predict 